import{s as f}from"./assets/vendor-b9f3e171.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function m(n){const r=document.querySelector(".gallery");r.innerHTML=n.map(({webformatURL:s,largeImageURL:i,tags:e,likes:t,views:o,comments:a,downloads:u})=>`<li class="gallery-item">
            <a href="${i}">
                <img src="${s}" alt="${e}" width="300" height="200" />
            </a>
            <p>likes: ${t}</p>
            <p>views: ${o}</p>
            <p>comments: ${a}</p>
            <p>downloads: ${u}</p>
        </li>`).join("")}function p(n){const o=`https://pixabay.com/api/?key=42468615-7a21ca39eb8f796f5c09d98b3&q=${n}&image_type=photo&orientation=horizontal&safesearch=${!0}`;return fetch(o).then(a=>{if(!a.ok)throw new Error("error while fetching");return a.json()})}const l=document.querySelector(".gallery"),d=document.querySelector("[data-search]");document.querySelector("[data-start]");const h=document.querySelector(".form-section"),y=new f(".gallery a",{captionData:"alt",captionDelay:250});let c="";l.innerHTML="";h.addEventListener("submit",g);function g(n){if(n.preventDefault(),c=d.value.trim(),!c){alert("fill the form");return}l.innerHTML="",p(c).then(r=>{r.hits.length===0?alert("we do not have ane images"):(m(r.hits),y.refresh())}).catch(r=>{console.error("Error fetching images:",r),alert(`Error: ${r.message}`)})}
//# sourceMappingURL=commonHelpers.js.map
